[package]
name = "kael_release"
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true
publish = true
description = "Release and update management for the Kael UI framework"
keywords = ["release", "updater", "auto-update", "kael"]
categories = ["development-tools"]
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
