[package]
edition.workspace = true
name = "kael_collections"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Standard collection type re-exports for Kael"
keywords = ["collections", "data-structures", "kael"]
categories = ["data-structures"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[features]
test-support = []

[lib]
name = "kael_collections"
path = "src/collections.rs"
doctest = false

[dependencies.indexmap]
version = "2.7.0"
features = ["serde"]

[dependencies.rustc-hash]
version = "2.1.0"


[lints]
workspace = true
