[package]
edition.workspace = true
name = "kael_collections"
autoexamples = false
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Fast deterministic collection aliases and standard collection re-exports for Kael"
documentation = "https://docs.rs/kael_collections"
keywords = ["collections", "data-structures", "kael"]
categories = ["data-structures"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true
exclude = ["examples/"]

[package.metadata.docs.rs]
targets = []

[features]
test-support = []

[lib]
name = "kael_collections"
path = "src/collections.rs"
doctest = true

[dependencies.indexmap]
version = "2.7.0"
features = ["serde"]

[dependencies.rustc-hash]
version = "2.1.0"


[lints]
workspace = true
