[package]
edition.workspace = true
name = "kael_semantic_version"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Semantic versioning library for Kael"
keywords = ["semver", "version", "versioning", "kael"]
categories = ["parser-implementations"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_semantic_version"
path = "src/semantic_version.rs"

[dependencies.anyhow]
workspace = true

[dependencies.serde]
workspace = true
features = [
    "derive",
    "rc",
]


[lints]
workspace = true
