[package]
autoexamples = false
edition.workspace = true
name = "kael_derive_refineable"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "A derive macro for creating refinement types in Rust for Kael"
documentation = "https://docs.rs/kael_derive_refineable"
keywords = ["derive", "macros", "refineable", "kael"]
categories = ["development-tools::procedural-macro-helpers", "rust-patterns"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true
exclude = ["examples/**"]

[package.metadata.docs.rs]
targets = []

[lib]
name = "kael_derive_refineable"
path = "src/derive_refineable.rs"
doctest = false
proc-macro = true

[dependencies.proc-macro2]
version = "1.0.93"

[dependencies.proc-macro-crate]
version = "3.5.0"

[dependencies.quote]
version = "1.0.9"

[dependencies.syn]
version = "2.0.101"
features = [
    "full",
    "extra-traits",
    "visit-mut",
]


[lints]
workspace = true
