[package]
edition.workspace = true
name = "kael_perf"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
autoexamples = false
description = "A tool for measuring test performance for Kael"
documentation = "https://docs.rs/kael_perf"
exclude = ["examples/**"]
keywords = ["performance", "profiling", "benchmark", "kael"]
categories = ["development-tools::profiling"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = []

[lib]
name = "kael_perf"
path = "src/lib.rs"

[[bin]]
name = "kael_perf"
path = "src/main.rs"

[dependencies.collections]
path = "../collections"
package = "kael_collections"
version = "0.3.0"

[dependencies.serde]
workspace = true
features = [
    "derive",
    "rc",
]

[dependencies.serde_json]
workspace = true
features = [
    "preserve_order",
    "raw_value",
]


[lints.clippy]
all = "warn"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
as_underscore = "deny"
let_underscore_must_use = "forbid"
missing_docs_in_private_items = "warn"
missing_safety_doc = "forbid"
needless_continue = "allow"
pedantic = "warn"
style = "warn"
undocumented_unsafe_blocks = "forbid"

[lints.clippy.disallowed_methods]
level = "allow"
priority = 1

[lints.rust]
missing_docs = "warn"
