[package]
edition.workspace = true
name = "kael_sum_tree"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "A sum tree data structure, a concurrency-friendly B-tree for Kael"
keywords = ["b-tree", "sumtree", "data-structures", "kael"]
categories = ["data-structures"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[package.metadata.docs.rs]
features = ["parallel"]

[features]
parallel = ["dep:rayon"]

[lib]
name = "kael_sum_tree"
path = "src/sum_tree.rs"
doctest = true

[dependencies.arrayvec]
version = "0.7.1"

[dependencies.rayon]
version = "1.8"
optional = true


[dev-dependencies.rand]
version = "0.9"

[lints]
workspace = true
