[package]
edition.workspace = true
name = "kael_sum_tree"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "A sum tree data structure, a concurrency-friendly B-tree for Kael"
keywords = ["b-tree", "sumtree", "data-structures", "kael"]
categories = ["data-structures"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_sum_tree"
path = "src/sum_tree.rs"
doctest = false

[dependencies.arrayvec]
version = "0.7.1"

[dependencies.log]
workspace = true
features = [
    "kv_unstable_serde",
    "serde",
]

[dependencies.rayon]
version = "1.8"


[dev-dependencies.rand]
version = "0.9"

[lints.clippy]
dbg_macro = "deny"
declare_interior_mutable_const = "deny"
disallowed_methods = "deny"
large_enum_variant = "allow"
let_underscore_future = "allow"
nonminimal_bool = "allow"
redundant_clone = "deny"
single_range_in_vec_init = "allow"
todo = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"
priority = 0
