[package]
edition.workspace = true
name = "kael_media_sys"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Focused macOS media interoperability for Kael"
keywords = ["media", "coremedia", "macos", "ffi", "kael"]
categories = ["multimedia", "os::macos-apis"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[package.metadata.docs.rs]
default-target = "aarch64-apple-darwin"
targets = []
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "kael_media_sys"
path = "src/media.rs"
doctest = false

[target.'cfg(target_os = "macos")'.dependencies.anyhow]
workspace = true

[target.'cfg(target_os = "macos")'.dependencies.core-foundation]
version = "0.10.0"

[target.'cfg(target_os = "macos")'.dependencies.core-video]
version = "0.4.3"
features = ["metal"]

[target.'cfg(target_os = "macos")'.dependencies.foreign-types]
version = "0.5"

[target.'cfg(target_os = "macos")'.dependencies.metal]
version = "0.29"

[lints]
workspace = true
