use image::{Frame, Rgba, RgbaImage};
use kael::{
    App, Application, Bounds, Context, ObjectFit, PrintImageStyle, PrintJob, PrintOrientation,
    PrintPage, PrintStroke, PrintTextStyle, RenderImage, SharedString, Window, WindowBounds,
    WindowOptions, div, img, point, prelude::*, px, rgb, size, white,
};
use smallvec::SmallVec;
use std::sync::Arc;

struct PrintDemo {
    preview_image: Arc<RenderImage>,
    status: SharedString,
}

fn button(text: &str, on_click: impl Fn(&mut Window, &mut App) + 'static) -> impl IntoElement {
    div()
        .id(SharedString::from(text.to_string()))
        .implicit_transitions()
        .flex_none()
        .px_2()
        .py_1()
        .bg(rgb(0xf7f7f7))
        .hover(|this| this.bg(rgb(0xefefef)).border_color(rgb(0xd8d8d8)))
        .active(|this| this.opacity(0.85).scale(0.985))
        .border_1()
        .border_color(rgb(0xe0e0e0))
        .rounded_sm()
        .cursor_pointer()
        .child(text.to_string())
        .on_click(move |_, window, cx| on_click(window, cx))
}

fn demo_page_size(landscape: bool) -> kael::Size<kael::Pixels> {
    if landscape {
        size(px(792.), px(612.))
    } else {
        size(px(612.), px(792.))
    }
}

fn build_preview_image() -> Arc<RenderImage> {
    let width = 240;
    let height = 140;
    let mut image = RgbaImage::new(width, height);

    for y in 0..height {
        for x in 0..width {
            let wave = (((x as f32 / width as f32) * std::f32::consts::TAU).sin() + 1.0) * 0.5;
            let red = (40.0 + 180.0 * (x as f32 / width as f32)) as u8;
            let green = (90.0 + 120.0 * (y as f32 / height as f32)) as u8;
            let blue = (120.0 + 100.0 * wave) as u8;
            image.put_pixel(x, y, Rgba([red, green, blue, 255]));
        }
    }

    for pixel in image.chunks_exact_mut(4) {
        pixel.swap(0, 2);
    }

    Arc::new(RenderImage::new(SmallVec::from_elem(Frame::new(image), 1)))
}

fn build_print_job(preview_image: Arc<RenderImage>, landscape: bool) -> PrintJob {
    let page_size = demo_page_size(landscape);
    let orientation = if landscape {
        PrintOrientation::Landscape
    } else {
        PrintOrientation::Portrait
    };

    PrintJob::new(if landscape {
        "GPUI Print Demo (Landscape)"
    } else {
        "GPUI Print Demo"
    })
    .orientation(orientation)
    .margins(px(36.))
    .page(PrintPage::new(page_size, move |print, _| {
        let content = print.bounds();
        let body_color = rgb(0xf6f0e6);
        let card_color = white();
        let ink = rgb(0x162433);
        let accent = rgb(0x0f766e);
        let accent_soft = rgb(0xd9f3ef);

        print.fill_rect(content, body_color);

        print.fill_rounded_rect(
            Bounds::new(point(px(18.), px(18.)), size(px(504.), px(130.))),
            px(22.),
            card_color,
        );
        print.draw_text(
            "GPUI Print Demo",
            point(px(42.), px(58.)),
            PrintTextStyle::new(px(28.)).color(ink),
        );
        print.draw_text_block(
            "This page is generated by the new print command buffer. It uses wrapped text, image drawing, and rounded or stroked rectangle primitives instead of relying on raw single-line text only.",
            Bounds::new(point(px(42.), px(84.)), size(px(438.), px(58.))),
            PrintTextStyle::new(px(13.)).color(rgb(0x415364)),
        );

        print.stroke_rect(
            Bounds::new(point(px(18.), px(170.)), size(px(240.), px(170.))),
            PrintStroke::new(px(2.)).color(accent),
        );
        print.draw_text(
            "Wrapped Text Block",
            point(px(38.), px(198.)),
            PrintTextStyle::new(px(17.)).color(ink),
        );
        print.draw_text_block(
            "The bounded text command wraps against a width constraint and stays inside the section frame, which is the missing primitive the first print pass did not have.",
            Bounds::new(point(px(38.), px(226.)), size(px(200.), px(92.))),
            PrintTextStyle::new(px(13.)).color(rgb(0x4c5f6f)),
        );

        print.fill_rounded_rect(
            Bounds::new(point(px(282.), px(170.)), size(px(240.), px(170.))),
            px(20.),
            accent_soft,
        );
        print.stroke_rounded_rect(
            Bounds::new(point(px(282.), px(170.)), size(px(240.), px(170.))),
            px(20.),
            PrintStroke::new(px(2.)).color(accent),
        );
        print.draw_text(
            "Image Primitive",
            point(px(306.), px(198.)),
            PrintTextStyle::new(px(17.)).color(ink),
        );
        print.draw_image_with_style(
            preview_image.clone(),
            Bounds::new(point(px(306.), px(224.)), size(px(190.), px(90.))),
            PrintImageStyle::new().object_fit(ObjectFit::Contain),
        );

        print.draw_text(
            "Shape Primitives",
            point(px(18.), px(386.)),
            PrintTextStyle::new(px(18.)).color(ink),
        );
        print.stroke_line(
            point(px(18.), px(412.)),
            point(px(522.), px(412.)),
            PrintStroke::new(px(1.)).color(rgb(0xb4a48a)),
        );
        print.fill_rect(
            Bounds::new(point(px(18.), px(436.)), size(px(110.), px(78.))),
            rgb(0xc9def2),
        );
        print.fill_rounded_rect(
            Bounds::new(point(px(146.), px(436.)), size(px(110.), px(78.))),
            px(18.),
            rgb(0xffd7b8),
        );
        print.stroke_rect(
            Bounds::new(point(px(274.), px(436.)), size(px(110.), px(78.))),
            PrintStroke::new(px(3.)).color(rgb(0x5f7890)),
        );
        print.stroke_rounded_rect(
            Bounds::new(point(px(402.), px(436.)), size(px(110.), px(78.))),
            px(18.),
            PrintStroke::new(px(3.)).color(rgb(0xb85c38)),
        );

        print.draw_text_block(
            if landscape {
                "Landscape mode uses the same command buffer and content blocks, but on a wider page size."
            } else {
                "Portrait mode is the default and mirrors the example preview shown in the app window."
            },
            Bounds::new(point(px(18.), px(546.)), size(px(504.), px(48.))),
            PrintTextStyle::new(px(13.)).color(rgb(0x556674)),
        );
    }))
}

impl Render for PrintDemo {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let entity = cx.entity();
        let preview_image = self.preview_image.clone();
        let status = self.status.clone();

        div()
            .size_full()
            .flex()
            .flex_col()
            .bg(rgb(0xf6f0e6))
            .text_color(rgb(0x162433))
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap_2()
                    .p_4()
                    .border_b_1()
                    .border_color(rgb(0xd7ccb9))
                    .bg(rgb(0xfffbf4))
                    .child(div().text_xl().font_weight(kael::FontWeight::SEMIBOLD).child("Print Demo"))
                    .child(
                        div()
                            .text_sm()
                            .text_color(rgb(0x5c6a77))
                            .child("Exercises wrapped print text, image drawing, and richer rectangle primitives."),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_wrap()
                            .gap_2()
                            .child(button("Dialog (Portrait)", {
                                let entity = entity.clone();
                                let preview_image = preview_image.clone();
                                move |window, cx| {
                                    let result =
                                        window.show_print_dialog(build_print_job(preview_image.clone(), false), cx);
                                    entity.update(cx, |this, cx| {
                                        this.status = match result {
                                            Ok(()) => "Opened the native portrait print dialog".into(),
                                            Err(err) => format!("Portrait print dialog failed: {err}").into(),
                                        };
                                        cx.notify();
                                    });
                                }
                            }))
                            .child(button("Dialog (Landscape)", {
                                let entity = entity.clone();
                                let preview_image = preview_image.clone();
                                move |window, cx| {
                                    let result =
                                        window.show_print_dialog(build_print_job(preview_image.clone(), true), cx);
                                    entity.update(cx, |this, cx| {
                                        this.status = match result {
                                            Ok(()) => "Opened the native landscape print dialog".into(),
                                            Err(err) => format!("Landscape print dialog failed: {err}").into(),
                                        };
                                        cx.notify();
                                    });
                                }
                            }))
                            .child(button("Direct Print", {
                                let entity = entity.clone();
                                let preview_image = preview_image.clone();
                                move |window, cx| {
                                    let result = window.print(build_print_job(preview_image.clone(), false), cx);
                                    entity.update(cx, |this, cx| {
                                        this.status = match result {
                                            Ok(()) => "Submitted the print job directly".into(),
                                            Err(err) => format!("Direct print failed: {err}").into(),
                                        };
                                        cx.notify();
                                    });
                                }
                            })),
                    )
                    .child(div().text_sm().child(format!("Status: {}", status))),
            )
            .child(
                div()
                    .flex_1()
                    .p_4()
                    .child(
                        div()
                            .max_w(px(720.))
                            .mx_auto()
                            .flex()
                            .flex_col()
                            .gap_4()
                            .child(
                                div()
                                    .rounded_xl()
                                    .border_1()
                                    .border_color(rgb(0xd8ccb8))
                                    .bg(white())
                                    .p_4()
                                    .child(div().text_lg().child("Preview Asset"))
                                    .child(
                                        div()
                                            .mt_3()
                                            .rounded_lg()
                                            .bg(rgb(0xf1f6fb))
                                            .border_1()
                                            .border_color(rgb(0xd7e5f1))
                                            .h(px(220.))
                                            .child(
                                                img(self.preview_image.clone())
                                                    .w_full()
                                                    .h_full()
                                                    .object_fit(ObjectFit::Contain),
                                            ),
                                    ),
                            )
                            .child(
                                div()
                                    .rounded_xl()
                                    .border_1()
                                    .border_color(rgb(0xd8ccb8))
                                    .bg(white())
                                    .p_4()
                                    .child(div().text_lg().child("What This Example Prints"))
                                    .child(
                                        div()
                                            .mt_3()
                                            .text_sm()
                                            .text_color(rgb(0x556674))
                                            .flex()
                                            .flex_col()
                                            .gap_2()
                                            .child("A wrapped text section bounded to a content box")
                                            .child("A generated image rendered through the new print image command")
                                            .child("Filled, stroked, and rounded rectangle primitives for layout accents"),
                                    ),
                            ),
                    ),
            )
    }
}

fn main() {
    Application::new().run(|cx: &mut App| {
        let bounds = Bounds::centered(None, size(px(960.), px(780.)), cx);
        cx.open_window(
            WindowOptions {
                window_bounds: Some(WindowBounds::Windowed(bounds)),
                ..Default::default()
            },
            |_, cx| {
                cx.new(|_| PrintDemo {
                    preview_image: build_preview_image(),
                    status: "Ready to open the native print flow".into(),
                })
            },
        )
        .unwrap();
        cx.activate(true);
    });
}
