[package]
edition.workspace = true
name = "kael-macros"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Macros for Kael"
keywords = ["macros", "derive", "gui", "kael", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers", "gui"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[features]
inspector = []

[lib]
name = "kael_macros"
path = "src/kael_macros.rs"
doctest = true
proc-macro = true

[[test]]
name = "compile_fail"
path = "tests/compile_fail.rs"

[[test]]
name = "derive_context"
path = "tests/derive_context.rs"

[[test]]
name = "derive_inspector_reflection"
path = "tests/derive_inspector_reflection.rs"

[[test]]
name = "render_test"
path = "tests/render_test.rs"

[dependencies.heck]
version = "0.5"

[dependencies.proc-macro2]
version = "1.0.93"

[dependencies.quote]
version = "1.0.9"

[dependencies.syn]
version = "2.0.101"
features = [
    "full",
    "extra-traits",
    "visit-mut",
]


[dev-dependencies]
kael = { package = "kael", path = "../kael" }
trybuild = "1"

[lints.clippy]
dbg_macro = "deny"
declare_interior_mutable_const = "deny"
disallowed_methods = "deny"
large_enum_variant = "allow"
let_underscore_future = "allow"
nonminimal_bool = "allow"
redundant_clone = "deny"
single_range_in_vec_init = "allow"
todo = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"
priority = 0
