[package]
edition.workspace = true
name = "kael_cache"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Bounded memory and content-addressed disk caching for Kael applications"
keywords = ["cache", "caching", "disk", "kael"]
categories = ["caching"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_cache"
path = "src/lib.rs"

[dependencies.anyhow]
workspace = true

[dependencies.serde]
workspace = true
features = ["derive"]

[dependencies.serde_json]
workspace = true

[dependencies.sha2]
version = "0.10"

[dependencies.tempfile]
version = "3.20.0"

[lints]
workspace = true
