[package]
edition.workspace = true
name = "kael_http_client"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "HTTP client library for Kael"
keywords = ["http", "client", "networking", "kael"]
categories = ["web-programming::http-client", "network-programming"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest", "dep:tokio"]
test-support = []

[lib]
name = "kael_http_client"
path = "src/http_client.rs"
doctest = true

[dependencies.anyhow]
workspace = true

[dependencies.bytes]
version = "1.0"

[dependencies.derive_more]
version = "2"
features = ["full"]

[dependencies.futures]
workspace = true

[dependencies.http]
version = "1.1"

[dependencies.http-body]
version = "1.0"

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.reqwest]
version = "0.12.24"
optional = true
features = [
    "charset",
    "http2",
    "macos-system-configuration",
    "rustls-tls-native-roots",
    "socks",
    "stream",
]
default-features = false

[dependencies.tokio]
version = "1.52.3"
optional = true
features = ["rt-multi-thread"]

[dependencies.url]
version = "2.2"

[lints]
workspace = true
