[package]
edition.workspace = true
name = "kael_http_client"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "HTTP client library for Kael"
keywords = ["http", "client", "networking", "kael"]
categories = ["web-programming::http-client", "network-programming"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[features]
test-support = []

[lib]
name = "kael_http_client"
path = "src/http_client.rs"
doctest = true

[dependencies.anyhow]
workspace = true

[dependencies.async-compression]
version = "0.4"
features = [
    "gzip",
    "futures-io",
]

[dependencies.async-fs]
version = "2.1"

[dependencies.async-tar]
version = "0.6.1"
default-features = false
features = ["runtime-tokio"]

[dependencies.bytes]
version = "1.0"

[dependencies.derive_more]
version = "2"
features = ["full"]

[dependencies.futures]
workspace = true

[dependencies.http]
version = "1.1"

[dependencies.http-body]
version = "1.0"

[dependencies.log]
workspace = true
features = [
    "kv_unstable_serde",
    "serde",
]

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.reqwest]
version = "0.12.24"
features = [
    "charset",
    "http2",
    "macos-system-configuration",
    "multipart",
    "rustls-tls-native-roots",
    "socks",
    "stream",
]
default-features = false

[dependencies.serde]
workspace = true
features = [
    "derive",
    "rc",
]

[dependencies.serde_json]
workspace = true
features = [
    "preserve_order",
    "raw_value",
]

[dependencies.sha2]
version = "0.10"

[dependencies.tempfile]
version = "3.20.0"

[dependencies.tokio]
version = "1.52.3"
features = ["rt-multi-thread"]

[dependencies.tokio-util]
version = "0.7"
features = ["compat"]

[dependencies.url]
version = "2.2"

[dependencies.util]
path = "../util"
package = "kael_util"
version = "0.3.0"


[lints]
workspace = true
