[package]
edition.workspace = true
name = "kael_audio"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Cross-platform audio playback, capture, mixing, DSP, and spatial services for Kael"
documentation = "https://docs.rs/kael_audio"
keywords = ["audio", "playback", "sound", "kael"]
categories = ["multimedia::audio"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = []

[lib]
name = "kael_audio"
path = "src/lib.rs"

[dependencies.anyhow]
workspace = true

[dependencies.cpal]
version = "0.15"

[dependencies.crossbeam-channel]
version = "0.5"

[dependencies.log]
workspace = true

[dependencies.kael_media]
path = "../kael-media"
package = "kael-media"
version = "0.3.1"

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.smol]
workspace = true

[dependencies.url]
version = "2.2"

[dev-dependencies.futures]
workspace = true

[lints]
workspace = true
