[package]
edition.workspace = true
name = "kael_audio"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Audio playback services for Kael"
keywords = ["audio", "playback", "sound", "kael"]
categories = ["multimedia::audio"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_audio"
path = "src/lib.rs"

[dependencies.anyhow]
workspace = true

[dependencies.cpal]
version = "0.15"

[dependencies.log]
workspace = true

[dependencies.kael_media]
path = "../kael-media"
package = "kael-media"
version = "0.3.0"

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.smol]
workspace = true

[dependencies.url]
version = "2.2"

[dev-dependencies.futures]
workspace = true

[lints]
workspace = true
