[package]
edition.workspace = true
name = "kael_refineable"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "A macro for creating refinement types for Kael"
keywords = ["refineable", "style", "patterns", "kael"]
categories = ["rust-patterns"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_refineable"
path = "src/refineable.rs"
doctest = false

[dependencies.derive_refineable]
path = "../derive_refineable"
package = "kael_derive_refineable"
version = "0.3.0"


[lints]
workspace = true
