[package]
name = "kael_i18n"
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true
publish = true
description = "Internationalization and localization support for the Kael UI framework"
keywords = ["i18n", "internationalization", "localization", "kael"]
categories = ["internationalization", "localization"]
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
