[package]
edition.workspace = true
name = "kael_pdf"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "PDF document services for Kael"
keywords = ["pdf", "rendering", "document", "kael"]
categories = ["multimedia", "rendering"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_pdf"
path = "src/lib.rs"
doctest = false

[dependencies.anyhow]
workspace = true

[dependencies.image]
version = "0.25.5"
default-features = false
features = ["png"]

[dependencies.lopdf]
version = "0.35"

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.serde]
workspace = true
features = ["derive"]

[dependencies.serde_json]
workspace = true

[dependencies.sha2]
version = "0.10"

[dependencies.smol]
workspace = true

[dev-dependencies.futures]
workspace = true

[dev-dependencies.tempfile]
version = "3.20.0"

[lints]
workspace = true
