[package]
edition.workspace = true
name = "kael_icons"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Platform services icon scaffolding for Kael"
keywords = ["icons", "native", "desktop", "kael"]
categories = ["gui", "os"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true
build = "build.rs"

[lib]
name = "kael_icons"
path = "src/lib.rs"
doctest = false

[lints.clippy]
dbg_macro = "deny"
declare_interior_mutable_const = "deny"
disallowed_methods = "deny"
large_enum_variant = "allow"
let_underscore_future = "allow"
nonminimal_bool = "allow"
redundant_clone = "deny"
single_range_in_vec_init = "allow"
todo = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"
priority = 0
