[package]
edition.workspace = true
name = "kael_icons"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Platform services icon scaffolding for Kael"
keywords = ["icons", "native", "desktop", "kael"]
categories = ["gui", "os"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true
build = "build.rs"

[lib]
name = "kael_icons"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true
