[package]
edition.workspace = true
name = "kael-media"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Audio playback primitives for GPUI"
keywords = ["media", "audio", "playback", "kael"]
categories = ["multimedia::audio", "multimedia"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_media"
path = "src/lib.rs"
doctest = false

[dependencies.ffmpeg-next]
version = "8.1.0"

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.rodio]
version = "0.20"

[dependencies.thiserror]
workspace = true

[lints]
workspace = true
