[package]
edition.workspace = true
name = "kael_notifications"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Notification services for Kael"
keywords = ["notifications", "desktop", "native", "kael"]
categories = ["os", "gui"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[lib]
name = "kael_notifications"
path = "src/lib.rs"
doctest = false

[dependencies.anyhow]
workspace = true

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.serde]
workspace = true
features = ["derive"]

[dev-dependencies.futures]
workspace = true

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies.zbus]
version = "5.18"
default-features = false
features = ["async-io", "blocking-api"]

[target.'cfg(target_os = "macos")'.dependencies.mac-notification-sys]
version = "0.6.15"

[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = [
    "Data_Xml_Dom",
    "Foundation",
    "UI_Notifications",
]

[lints]
workspace = true
