[package]
name = "kael_net"
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true
publish = true
description = "Networking and sync primitives for the Kael UI framework"
keywords = ["networking", "http", "sync", "kael"]
categories = ["network-programming"]
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
fastrand = "2"
kael_secrets = { path = "../kael_secrets", version = "0.3.0" }
