use proc_macro::TokenStream;
use proc_macro2::{Ident, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::parse_macro_input;

pub(crate) fn register_action(ident: TokenStream) -> TokenStream {
    let name = parse_macro_input!(ident as Ident);
    let kael = match crate::kael_crate_path() {
        Ok(path) => path,
        Err(error) => return error.into_compile_error().into(),
    };
    let registration = generate_register_action(&name, &kael);

    TokenStream::from(quote! {
        #registration
    })
}

pub(crate) fn generate_register_action(type_name: &Ident, kael: &syn::Path) -> TokenStream2 {
    let action_builder_fn_name = format_ident!(
        "__kael_actions_builder_{}",
        type_name.to_string().to_lowercase()
    );

    quote! {
        impl #type_name {
            /// This is an auto generated function, do not use.
            #[automatically_derived]
            #[doc(hidden)]
            fn __autogenerated() {
                /// This is an auto generated function, do not use.
                #[doc(hidden)]
                fn #action_builder_fn_name() -> #kael::MacroActionData {
                    #kael::MacroActionData {
                        name: <#type_name as #kael::Action>::name_for_type(),
                        type_id: ::std::any::TypeId::of::<#type_name>(),
                        build: <#type_name as #kael::Action>::build,
                        json_schema: <#type_name as #kael::Action>::action_json_schema,
                        deprecated_aliases: <#type_name as #kael::Action>::deprecated_aliases(),
                        deprecation_message: <#type_name as #kael::Action>::deprecation_message(),
                        documentation: <#type_name as #kael::Action>::documentation(),
                    }
                }

                #kael::private::inventory::submit! {
                    #kael::MacroActionBuilder(#action_builder_fn_name)
                }
            }
        }
    }
}
