use crate::{
    Bounds, Capslock, Context, Empty, IntoElement, Keystroke, Modifiers, Pixels, Point, Render,
    Window, point, seal::Sealed,
};
use http_client::Url;
use smallvec::SmallVec;
use std::{any::Any, fmt::Debug, ops::Deref, path::PathBuf, sync::OnceLock};

/// An event from a platform input source.
pub trait InputEvent: Sealed + 'static {
    /// Convert this event into the platform input enum.
    fn to_platform_input(self) -> PlatformInput;
}

/// A key event from the platform.
pub trait KeyEvent: InputEvent {}

/// A mouse event from the platform.
pub trait MouseEvent: InputEvent {}

/// The key down event equivalent for the platform.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KeyDownEvent {
    /// The keystroke that was generated.
    pub keystroke: Keystroke,

    /// Whether the key is currently held down.
    pub is_held: bool,
}

impl Sealed for KeyDownEvent {}
impl InputEvent for KeyDownEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::KeyDown(self)
    }
}
impl KeyEvent for KeyDownEvent {}

/// The key up event equivalent for the platform.
#[derive(Clone, Debug)]
pub struct KeyUpEvent {
    /// The keystroke that was released.
    pub keystroke: Keystroke,
}

impl Sealed for KeyUpEvent {}
impl InputEvent for KeyUpEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::KeyUp(self)
    }
}
impl KeyEvent for KeyUpEvent {}

/// The modifiers changed event equivalent for the platform.
#[derive(Clone, Debug, Default)]
pub struct ModifiersChangedEvent {
    /// The new state of the modifier keys
    pub modifiers: Modifiers,
    /// The new state of the capslock key
    pub capslock: Capslock,
}

impl Sealed for ModifiersChangedEvent {}
impl InputEvent for ModifiersChangedEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::ModifiersChanged(self)
    }
}
impl KeyEvent for ModifiersChangedEvent {}

impl Deref for ModifiersChangedEvent {
    type Target = Modifiers;

    fn deref(&self) -> &Self::Target {
        &self.modifiers
    }
}

/// The phase of a touch motion event.
/// Based on the winit enum of the same name.
#[derive(Clone, Copy, Debug, Default)]
pub enum TouchPhase {
    /// The touch started.
    Started,
    /// The touch event is moving.
    #[default]
    Moved,
    /// The touch phase has ended
    Ended,
}

/// A mouse down event from the platform
#[derive(Clone, Debug, Default)]
pub struct MouseDownEvent {
    /// Which mouse button was pressed.
    pub button: MouseButton,

    /// The position of the mouse on the window.
    pub position: Point<Pixels>,

    /// The modifiers that were held down when the mouse was pressed.
    pub modifiers: Modifiers,

    /// The number of times the button has been clicked.
    pub click_count: usize,

    /// Whether this is the first, focusing click.
    pub first_mouse: bool,
}

impl Sealed for MouseDownEvent {}
impl InputEvent for MouseDownEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::MouseDown(self)
    }
}
impl MouseEvent for MouseDownEvent {}

/// A mouse up event from the platform
#[derive(Clone, Debug, Default)]
pub struct MouseUpEvent {
    /// Which mouse button was released.
    pub button: MouseButton,

    /// The position of the mouse on the window.
    pub position: Point<Pixels>,

    /// The modifiers that were held down when the mouse was released.
    pub modifiers: Modifiers,

    /// The number of times the button has been clicked.
    pub click_count: usize,
}

impl Sealed for MouseUpEvent {}
impl InputEvent for MouseUpEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::MouseUp(self)
    }
}
impl MouseEvent for MouseUpEvent {}

/// A click event, generated when a mouse button is pressed and released.
#[derive(Clone, Debug, Default)]
pub struct MouseClickEvent {
    /// The mouse event when the button was pressed.
    pub down: MouseDownEvent,

    /// The mouse event when the button was released.
    pub up: MouseUpEvent,
}

/// A click event that was generated by a keyboard button being pressed and released.
#[derive(Clone, Debug, Default)]
pub struct KeyboardClickEvent {
    /// The keyboard button that was pressed to trigger the click.
    pub button: KeyboardButton,

    /// The bounds of the element that was clicked.
    pub bounds: Bounds<Pixels>,
}

/// A click event, generated when a mouse button or keyboard button is pressed and released.
#[derive(Clone, Debug)]
pub enum ClickEvent {
    /// A click event trigger by a mouse button being pressed and released.
    Mouse(MouseClickEvent),
    /// A click event trigger by a keyboard button being pressed and released.
    Keyboard(KeyboardClickEvent),
}

impl Default for ClickEvent {
    fn default() -> Self {
        ClickEvent::Keyboard(KeyboardClickEvent::default())
    }
}

impl ClickEvent {
    /// Returns the modifiers that were held during the click event
    ///
    /// `Keyboard`: The keyboard click events never have modifiers.
    /// `Mouse`: Modifiers that were held during the mouse key up event.
    pub fn modifiers(&self) -> Modifiers {
        match self {
            // Click events are only generated from keyboard events _without any modifiers_, so we know the modifiers are always Default
            ClickEvent::Keyboard(_) => Modifiers::default(),
            // Click events on the web only reflect the modifiers for the keyup event,
            // tested via observing the behavior of the `ClickEvent.shiftKey` field in Chrome 138
            // under various combinations of modifiers and keyUp / keyDown events.
            ClickEvent::Mouse(event) => event.up.modifiers,
        }
    }

    /// Returns the position of the click event
    ///
    /// `Keyboard`: The bottom left corner of the clicked hitbox
    /// `Mouse`: The position of the mouse when the button was released.
    pub fn position(&self) -> Point<Pixels> {
        match self {
            ClickEvent::Keyboard(event) => event.bounds.bottom_left(),
            ClickEvent::Mouse(event) => event.up.position,
        }
    }

    /// Returns the mouse position of the click event
    ///
    /// `Keyboard`: None
    /// `Mouse`: The position of the mouse when the button was released.
    pub fn mouse_position(&self) -> Option<Point<Pixels>> {
        match self {
            ClickEvent::Keyboard(_) => None,
            ClickEvent::Mouse(event) => Some(event.up.position),
        }
    }

    /// Returns if this was a right click
    ///
    /// `Keyboard`: false
    /// `Mouse`: Whether the right button was pressed and released
    pub fn is_right_click(&self) -> bool {
        match self {
            ClickEvent::Keyboard(_) => false,
            ClickEvent::Mouse(event) => {
                event.down.button == MouseButton::Right && event.up.button == MouseButton::Right
            }
        }
    }

    /// Returns whether the click was a standard click
    ///
    /// `Keyboard`: Always true
    /// `Mouse`: Left button pressed and released
    pub fn standard_click(&self) -> bool {
        match self {
            ClickEvent::Keyboard(_) => true,
            ClickEvent::Mouse(event) => {
                event.down.button == MouseButton::Left && event.up.button == MouseButton::Left
            }
        }
    }

    /// Returns whether the click focused the element
    ///
    /// `Keyboard`: false, keyboard clicks only work if an element is already focused
    /// `Mouse`: Whether this was the first focusing click
    pub fn first_focus(&self) -> bool {
        match self {
            ClickEvent::Keyboard(_) => false,
            ClickEvent::Mouse(event) => event.down.first_mouse,
        }
    }

    /// Returns the click count of the click event
    ///
    /// `Keyboard`: Always 1
    /// `Mouse`: Count of clicks from MouseUpEvent
    pub fn click_count(&self) -> usize {
        match self {
            ClickEvent::Keyboard(_) => 1,
            ClickEvent::Mouse(event) => event.up.click_count,
        }
    }

    /// Returns whether the click event is generated by a keyboard event
    pub fn is_keyboard(&self) -> bool {
        match self {
            ClickEvent::Mouse(_) => false,
            ClickEvent::Keyboard(_) => true,
        }
    }
}

/// An enum representing the keyboard button that was pressed for a click event.
#[derive(Hash, PartialEq, Eq, Copy, Clone, Debug, Default)]
pub enum KeyboardButton {
    /// Enter key was clicked
    #[default]
    Enter,
    /// Space key was clicked
    Space,
}

/// An enum representing the mouse button that was pressed.
#[derive(Hash, PartialEq, Eq, Copy, Clone, Debug, Default)]
pub enum MouseButton {
    /// The left mouse button.
    #[default]
    Left,

    /// The right mouse button.
    Right,

    /// The middle mouse button.
    Middle,

    /// A navigation button, such as back or forward.
    Navigate(NavigationDirection),
}

impl MouseButton {
    /// Get all the mouse buttons in a list.
    pub fn all() -> Vec<Self> {
        vec![
            MouseButton::Left,
            MouseButton::Right,
            MouseButton::Middle,
            MouseButton::Navigate(NavigationDirection::Back),
            MouseButton::Navigate(NavigationDirection::Forward),
        ]
    }
}

/// A navigation direction, such as back or forward.
#[derive(Hash, PartialEq, Eq, Copy, Clone, Debug, Default)]
pub enum NavigationDirection {
    /// The back button.
    #[default]
    Back,

    /// The forward button.
    Forward,
}

/// A mouse move event from the platform
#[derive(Clone, Debug, Default)]
pub struct MouseMoveEvent {
    /// The position of the mouse on the window.
    pub position: Point<Pixels>,

    /// The mouse button that was pressed, if any.
    pub pressed_button: Option<MouseButton>,

    /// The modifiers that were held down when the mouse was moved.
    pub modifiers: Modifiers,
}

impl Sealed for MouseMoveEvent {}
impl InputEvent for MouseMoveEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::MouseMove(self)
    }
}
impl MouseEvent for MouseMoveEvent {}

impl MouseMoveEvent {
    /// Returns true if the left mouse button is currently held down.
    pub fn dragging(&self) -> bool {
        self.pressed_button == Some(MouseButton::Left)
    }
}

/// A mouse wheel event from the platform
#[derive(Clone, Debug, Default)]
pub struct ScrollWheelEvent {
    /// The position of the mouse on the window.
    pub position: Point<Pixels>,

    /// The change in scroll wheel position for this event.
    pub delta: ScrollDelta,

    /// The modifiers that were held down when the mouse was moved.
    pub modifiers: Modifiers,

    /// The phase of the touch event.
    pub touch_phase: TouchPhase,

    /// Whether this event is part of inertial scrolling after direct touch input ends.
    pub is_momentum: bool,
}

impl Sealed for ScrollWheelEvent {}
impl InputEvent for ScrollWheelEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::ScrollWheel(self)
    }
}
impl MouseEvent for ScrollWheelEvent {}

impl Deref for ScrollWheelEvent {
    type Target = Modifiers;

    fn deref(&self) -> &Self::Target {
        &self.modifiers
    }
}

/// A magnification gesture event from the platform.
#[derive(Clone, Debug, Default)]
pub struct MagnifyEvent {
    /// The position of the gesture in window coordinates.
    pub position: Point<Pixels>,

    /// The incremental magnification delta for this event.
    pub delta: f32,

    /// The modifiers that were held when the gesture fired.
    pub modifiers: Modifiers,

    /// The touch phase associated with the gesture.
    pub touch_phase: TouchPhase,
}

impl Sealed for MagnifyEvent {}
impl InputEvent for MagnifyEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::Magnify(self)
    }
}
impl MouseEvent for MagnifyEvent {}

impl Deref for MagnifyEvent {
    type Target = Modifiers;

    fn deref(&self) -> &Self::Target {
        &self.modifiers
    }
}

/// The scroll delta for a scroll wheel event.
#[derive(Clone, Copy, Debug)]
pub enum ScrollDelta {
    /// An exact scroll delta in pixels.
    Pixels(Point<Pixels>),
    /// An inexact scroll delta in lines.
    Lines(Point<f32>),
}

impl Default for ScrollDelta {
    fn default() -> Self {
        Self::Lines(Default::default())
    }
}

impl ScrollDelta {
    /// Returns true if this is a precise scroll delta in pixels.
    pub fn precise(&self) -> bool {
        match self {
            ScrollDelta::Pixels(_) => true,
            ScrollDelta::Lines(_) => false,
        }
    }

    /// Converts this scroll event into exact pixels.
    pub fn pixel_delta(&self, line_height: Pixels) -> Point<Pixels> {
        match self {
            ScrollDelta::Pixels(delta) => *delta,
            ScrollDelta::Lines(delta) => point(line_height * delta.x, line_height * delta.y),
        }
    }

    pub(crate) fn trace_label(&self) -> String {
        match self {
            ScrollDelta::Pixels(delta) => {
                format!(
                    "pixels({:.2},{:.2})",
                    f32::from(delta.x),
                    f32::from(delta.y)
                )
            }
            ScrollDelta::Lines(delta) => format!("lines({:.2},{:.2})", delta.x, delta.y),
        }
    }

    /// Combines two scroll deltas into one.
    /// If the signs of the deltas are the same (both positive or both negative),
    /// the deltas are added together. If the signs are opposite, the second delta
    /// (other) is used, effectively overriding the first delta.
    pub fn coalesce(self, other: ScrollDelta) -> ScrollDelta {
        match (self, other) {
            (ScrollDelta::Pixels(a), ScrollDelta::Pixels(b)) => {
                let x = if a.x.signum() == b.x.signum() {
                    a.x + b.x
                } else {
                    b.x
                };

                let y = if a.y.signum() == b.y.signum() {
                    a.y + b.y
                } else {
                    b.y
                };

                ScrollDelta::Pixels(point(x, y))
            }

            (ScrollDelta::Lines(a), ScrollDelta::Lines(b)) => {
                let x = if a.x.signum() == b.x.signum() {
                    a.x + b.x
                } else {
                    b.x
                };

                let y = if a.y.signum() == b.y.signum() {
                    a.y + b.y
                } else {
                    b.y
                };

                ScrollDelta::Lines(point(x, y))
            }

            _ => other,
        }
    }
}

pub(crate) fn scroll_trace_enabled() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    *ENABLED.get_or_init(|| {
        std::env::var("KAEL_SCROLL_TRACE")
            .map(|value| {
                let value = value.trim().to_ascii_lowercase();
                !value.is_empty() && value != "0" && value != "false" && value != "off"
            })
            .unwrap_or(false)
    })
}

/// A mouse exit event from the platform, generated when the mouse leaves the window.
#[derive(Clone, Debug, Default)]
pub struct MouseExitEvent {
    /// The position of the mouse relative to the window.
    pub position: Point<Pixels>,
    /// The mouse button that was pressed, if any.
    pub pressed_button: Option<MouseButton>,
    /// The modifiers that were held down when the mouse was moved.
    pub modifiers: Modifiers,
}

impl Sealed for MouseExitEvent {}
impl InputEvent for MouseExitEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::MouseExited(self)
    }
}
impl MouseEvent for MouseExitEvent {}

impl Deref for MouseExitEvent {
    type Target = Modifiers;

    fn deref(&self) -> &Self::Target {
        &self.modifiers
    }
}

/// A collection of paths from the platform, such as from a file drop.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExternalPaths(pub(crate) SmallVec<[PathBuf; 2]>);

impl ExternalPaths {
    /// Create an empty collection of external paths.
    pub fn new() -> Self {
        Self(SmallVec::new())
    }

    /// Create a collection from platform or test paths.
    pub fn from_paths(paths: impl IntoIterator<Item = PathBuf>) -> Self {
        Self(paths.into_iter().collect())
    }

    /// Convert this collection of paths into a slice.
    pub fn paths(&self) -> &[PathBuf] {
        &self.0
    }

    /// Iterate over the paths.
    pub fn iter(&self) -> impl Iterator<Item = &PathBuf> {
        self.0.iter()
    }

    /// Return the first path, if any.
    pub fn first(&self) -> Option<&PathBuf> {
        self.0.first()
    }

    /// Return the number of paths.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Return whether no paths are present.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Return an owned vector of paths.
    pub fn to_vec(&self) -> Vec<PathBuf> {
        self.0.to_vec()
    }

    /// Apply a drop-zone filter to this path collection.
    pub fn filter_with(&self, filter: &FileDropFilter) -> FileDropMatch {
        filter.evaluate(self)
    }

    /// Return accepted paths when every dropped path is accepted by the filter.
    pub fn accepted_by(&self, filter: &FileDropFilter) -> Option<Vec<PathBuf>> {
        self.filter_with(filter).into_clean_accept()
    }

    /// Convert this file-only payload into a general external drop payload.
    pub fn into_drop_data(self) -> ExternalDropData {
        ExternalDropData::from_paths(self.0)
    }
}

impl Render for ExternalPaths {
    fn render(&mut self, _: &mut Window, _: &mut Context<Self>) -> impl IntoElement {
        // the platform will render icons for the dragged files
        Empty
    }
}

/// Data dragged from outside the app, such as browser-style file, text, or URL payloads.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExternalDropData {
    paths: ExternalPaths,
    text: Option<String>,
    urls: Vec<String>,
}

impl ExternalDropData {
    /// Create an empty external drop payload.
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a file-only external drop payload.
    pub fn from_paths(paths: impl IntoIterator<Item = PathBuf>) -> Self {
        Self {
            paths: ExternalPaths::from_paths(paths),
            text: None,
            urls: Vec::new(),
        }
    }

    /// Create a text-only external drop payload.
    pub fn text(text: impl Into<String>) -> Self {
        Self::new().with_text(text)
    }

    /// Create a URL-only external drop payload.
    pub fn url(url: impl Into<String>) -> Self {
        Self::new().with_url(url)
    }

    /// Normalize a typed drag payload into browser-style external drop data.
    ///
    /// This accepts both file-only [`ExternalPaths`] payloads and richer
    /// [`ExternalDropData`] payloads emitted by native text/URL drops or custom
    /// WebView bridges.
    pub fn from_drag_value(value: &dyn Any) -> Option<Self> {
        value.downcast_ref::<Self>().cloned().or_else(|| {
            value
                .downcast_ref::<ExternalPaths>()
                .cloned()
                .map(Into::into)
        })
    }

    /// Parse `text/uri-list` data into file paths and URLs.
    ///
    /// Lines beginning with `#` are comments per the freedesktop/URI-list
    /// convention. `file://` entries become paths; other URI schemes stay in
    /// the URL list.
    pub fn from_uri_list(uri_list: &str) -> Self {
        let mut paths = SmallVec::<[PathBuf; 2]>::new();
        let mut urls = Vec::new();

        for line in uri_list.lines().map(str::trim) {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            match Url::parse(line) {
                Ok(url) => match url.to_file_path() {
                    Ok(path) => paths.push(path),
                    Err(_) => urls.push(line.to_string()),
                },
                Err(_) => urls.push(line.to_string()),
            }
        }

        Self {
            paths: ExternalPaths(paths),
            text: None,
            urls,
        }
    }

    /// Create a payload from plain text and extract URL-looking lines.
    pub fn from_plain_text(text: impl Into<String>) -> Self {
        let text = text.into();
        let urls = text
            .lines()
            .map(str::trim)
            .filter(|line| Url::parse(line).is_ok())
            .map(str::to_string)
            .collect();
        Self {
            paths: ExternalPaths::new(),
            text: Some(text),
            urls,
        }
    }

    /// Set plain text carried by the drop.
    pub fn with_text(mut self, text: impl Into<String>) -> Self {
        self.text = Some(text.into());
        self
    }

    /// Add one URL carried by the drop.
    pub fn with_url(mut self, url: impl Into<String>) -> Self {
        self.urls.push(url.into());
        self
    }

    /// Add many URLs carried by the drop.
    pub fn with_urls(mut self, urls: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.urls.extend(urls.into_iter().map(Into::into));
        self
    }

    /// Return file paths carried by the drop.
    pub fn paths(&self) -> &ExternalPaths {
        &self.paths
    }

    /// Return plain text carried by the drop, if any.
    pub fn text_value(&self) -> Option<&str> {
        self.text.as_deref()
    }

    /// Return URLs carried by the drop.
    pub fn urls(&self) -> &[String] {
        &self.urls
    }

    /// Return true when file paths are present.
    pub fn has_paths(&self) -> bool {
        !self.paths.is_empty()
    }

    /// Return true when text is present and not empty.
    pub fn has_text(&self) -> bool {
        self.text_value().is_some_and(|text| !text.is_empty())
    }

    /// Return true when URLs are present.
    pub fn has_urls(&self) -> bool {
        !self.urls.is_empty()
    }

    /// Return accepted file paths when every dropped file path is accepted by the filter.
    pub fn accepted_paths_by(&self, filter: &FileDropFilter) -> Option<Vec<PathBuf>> {
        self.paths.accepted_by(filter)
    }

    /// Return whether this payload can be accepted by a file-oriented drop zone.
    ///
    /// File payloads must pass the filter. Text/URL-only payloads are accepted
    /// because there are no file paths to reject.
    pub fn accepted_by(&self, filter: &FileDropFilter) -> bool {
        if self.has_paths() {
            self.accepted_paths_by(filter).is_some()
        } else {
            self.has_text() || self.has_urls()
        }
    }
}

impl Render for ExternalDropData {
    fn render(&mut self, _: &mut Window, _: &mut Context<Self>) -> impl IntoElement {
        Empty
    }
}

impl From<ExternalPaths> for ExternalDropData {
    fn from(paths: ExternalPaths) -> Self {
        paths.into_drop_data()
    }
}

/// Builder for accepting dropped files by count and extension.
#[derive(Debug, Clone, Default)]
pub struct FileDropFilter {
    allowed_extensions: Vec<String>,
    max_files: Option<usize>,
}

impl FileDropFilter {
    /// Create a filter that accepts any path count and extension.
    pub fn new() -> Self {
        Self::default()
    }

    /// Accept one file with any extension.
    pub fn single_file() -> Self {
        Self::new().max_files(1)
    }

    /// Accept common image file extensions.
    pub fn images() -> Self {
        Self::new().extensions([
            "avif", "bmp", "gif", "heic", "heif", "jpg", "jpeg", "png", "webp",
        ])
    }

    /// Accept common audio file extensions.
    pub fn audio() -> Self {
        Self::new().extensions(["aac", "aiff", "flac", "m4a", "mp3", "ogg", "opus", "wav"])
    }

    /// Accept common video file extensions.
    pub fn video() -> Self {
        Self::new().extensions([
            "avi", "m4v", "mkv", "mov", "mp4", "mpeg", "mpg", "ogv", "webm",
        ])
    }

    /// Accept common audio and video file extensions.
    pub fn media() -> Self {
        Self::new().extensions([
            "aac", "aiff", "avi", "flac", "m4a", "m4v", "mkv", "mov", "mp3", "mp4", "mpeg", "mpg",
            "ogg", "ogv", "opus", "wav", "webm",
        ])
    }

    /// Accept only paths with one of the provided extensions.
    ///
    /// Extensions are matched case-insensitively and may be passed with or
    /// without a leading dot.
    pub fn extensions(mut self, extensions: impl IntoIterator<Item = impl AsRef<str>>) -> Self {
        self.allowed_extensions = extensions
            .into_iter()
            .map(|extension| normalize_file_extension(extension.as_ref()))
            .filter(|extension| !extension.is_empty())
            .collect();
        self.allowed_extensions.sort();
        self.allowed_extensions.dedup();
        self
    }

    /// Accept at most this many paths.
    pub fn max_files(mut self, max_files: usize) -> Self {
        self.max_files = Some(max_files);
        self
    }

    /// Return the allowed extensions.
    pub fn allowed_extensions(&self) -> &[String] {
        &self.allowed_extensions
    }

    /// Return the configured max file count.
    pub fn configured_max_files(&self) -> Option<usize> {
        self.max_files
    }

    /// Validate the filter configuration.
    pub fn validate(&self) -> anyhow::Result<()> {
        if let Some(max_files) = self.max_files {
            anyhow::ensure!(
                max_files > 0,
                "file drop max_files must be greater than zero"
            );
        }
        Ok(())
    }

    /// Return whether the given path would be accepted by this filter before
    /// considering max file count.
    pub fn accepts_path(&self, path: &std::path::Path) -> bool {
        if self.allowed_extensions.is_empty() {
            return true;
        }

        path.extension()
            .and_then(|extension| extension.to_str())
            .map(normalize_file_extension)
            .is_some_and(|extension| self.allowed_extensions.contains(&extension))
    }

    /// Evaluate a set of dropped paths.
    pub fn evaluate(&self, paths: &ExternalPaths) -> FileDropMatch {
        let mut accepted = Vec::new();
        let mut rejected = Vec::new();

        for path in paths.iter() {
            let allowed_by_extension = self.accepts_path(path);
            let allowed_by_count = self
                .max_files
                .is_none_or(|max_files| accepted.len() < max_files);

            if allowed_by_extension && allowed_by_count {
                accepted.push(path.clone());
            } else {
                rejected.push(path.clone());
            }
        }

        FileDropMatch { accepted, rejected }
    }
}

/// Accepted and rejected paths from a file drop.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileDropMatch {
    accepted: Vec<PathBuf>,
    rejected: Vec<PathBuf>,
}

impl FileDropMatch {
    /// Paths accepted by the filter.
    pub fn accepted(&self) -> &[PathBuf] {
        &self.accepted
    }

    /// Paths rejected by the filter.
    pub fn rejected(&self) -> &[PathBuf] {
        &self.rejected
    }

    /// Consume this match into accepted paths.
    pub fn into_accepted(self) -> Vec<PathBuf> {
        self.accepted
    }

    /// Return true when all dropped paths were accepted and at least one path was present.
    pub fn is_clean_accept(&self) -> bool {
        !self.accepted.is_empty() && self.rejected.is_empty()
    }

    /// Return true when no path was accepted.
    pub fn is_empty_accept(&self) -> bool {
        self.accepted.is_empty()
    }

    /// Consume this match into accepted paths only when the drop was clean.
    pub fn into_clean_accept(self) -> Option<Vec<PathBuf>> {
        self.is_clean_accept().then_some(self.accepted)
    }
}

fn normalize_file_extension(extension: &str) -> String {
    extension
        .trim()
        .trim_start_matches('.')
        .to_ascii_lowercase()
}

/// A file drop event from the platform, generated when files are dragged and dropped onto the window.
#[derive(Debug, Clone)]
pub enum FileDropEvent {
    /// The files have entered the window.
    Entered {
        /// The position of the mouse relative to the window.
        position: Point<Pixels>,
        /// The paths of the files that are being dragged.
        paths: ExternalPaths,
    },
    /// External drop data has entered the window.
    DataEntered {
        /// The position of the mouse relative to the window.
        position: Point<Pixels>,
        /// The browser-style files/text/URLs payload being dragged.
        data: ExternalDropData,
    },
    /// The files are being dragged over the window
    Pending {
        /// The position of the mouse relative to the window.
        position: Point<Pixels>,
    },
    /// The files have been dropped onto the window.
    Submit {
        /// The position of the mouse relative to the window.
        position: Point<Pixels>,
    },
    /// The user has stopped dragging the files over the window.
    Exited,
}

impl Sealed for FileDropEvent {}
impl InputEvent for FileDropEvent {
    fn to_platform_input(self) -> PlatformInput {
        PlatformInput::FileDrop(self)
    }
}
impl MouseEvent for FileDropEvent {}

/// An enum corresponding to all kinds of platform input events.
#[derive(Clone, Debug)]
pub enum PlatformInput {
    /// A key was pressed.
    KeyDown(KeyDownEvent),
    /// A key was released.
    KeyUp(KeyUpEvent),
    /// The keyboard modifiers were changed.
    ModifiersChanged(ModifiersChangedEvent),
    /// The mouse was pressed.
    MouseDown(MouseDownEvent),
    /// The mouse was released.
    MouseUp(MouseUpEvent),
    /// The mouse was moved.
    MouseMove(MouseMoveEvent),
    /// The mouse exited the window.
    MouseExited(MouseExitEvent),
    /// The scroll wheel was used.
    ScrollWheel(ScrollWheelEvent),
    /// A magnification gesture was used.
    Magnify(MagnifyEvent),
    /// Files were dragged and dropped onto the window.
    FileDrop(FileDropEvent),
}

impl PlatformInput {
    pub(crate) fn mouse_event(&self) -> Option<&dyn Any> {
        match self {
            PlatformInput::KeyDown { .. } => None,
            PlatformInput::KeyUp { .. } => None,
            PlatformInput::ModifiersChanged { .. } => None,
            PlatformInput::MouseDown(event) => Some(event),
            PlatformInput::MouseUp(event) => Some(event),
            PlatformInput::MouseMove(event) => Some(event),
            PlatformInput::MouseExited(event) => Some(event),
            PlatformInput::ScrollWheel(event) => Some(event),
            PlatformInput::Magnify(event) => Some(event),
            PlatformInput::FileDrop(event) => Some(event),
        }
    }

    pub(crate) fn keyboard_event(&self) -> Option<&dyn Any> {
        match self {
            PlatformInput::KeyDown(event) => Some(event),
            PlatformInput::KeyUp(event) => Some(event),
            PlatformInput::ModifiersChanged(event) => Some(event),
            PlatformInput::MouseDown(_) => None,
            PlatformInput::MouseUp(_) => None,
            PlatformInput::MouseMove(_) => None,
            PlatformInput::MouseExited(_) => None,
            PlatformInput::ScrollWheel(_) => None,
            PlatformInput::Magnify(_) => None,
            PlatformInput::FileDrop(_) => None,
        }
    }
}

#[cfg(test)]
mod test {
    use std::path::PathBuf;

    use crate::{
        AppContext as _, Context, ExternalDropData, ExternalPaths, FileDropFilter, FocusHandle,
        InteractiveElement, IntoElement, KeyBinding, Keystroke, ParentElement, Render,
        TestAppContext, Window, div,
    };

    struct TestView {
        saw_key_down: bool,
        saw_action: bool,
        focus_handle: FocusHandle,
    }

    actions!(test_only, [TestAction]);

    impl Render for TestView {
        fn render(&mut self, _: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
            div().id("testview").child(
                div()
                    .key_context("parent")
                    .on_key_down(cx.listener(|this, _, _, cx| {
                        cx.stop_propagation();
                        this.saw_key_down = true
                    }))
                    .on_action(cx.listener(|this: &mut TestView, _: &TestAction, _, _| {
                        this.saw_action = true
                    }))
                    .child(
                        div()
                            .key_context("nested")
                            .track_focus(&self.focus_handle)
                            .into_element(),
                    ),
            )
        }
    }

    #[kael::test]
    fn test_on_events(cx: &mut TestAppContext) {
        let window = cx.update(|cx| {
            cx.open_window(crate::WindowOptions::default(), |_, cx| {
                cx.new(|cx| TestView {
                    saw_key_down: false,
                    saw_action: false,
                    focus_handle: cx.focus_handle(),
                })
            })
            .unwrap()
        });

        cx.update(|cx| {
            cx.bind_keys(vec![KeyBinding::new("ctrl-g", TestAction, Some("parent"))]);
        });

        window
            .update(cx, |test_view, window, _cx| {
                window.focus(&test_view.focus_handle)
            })
            .unwrap();

        cx.dispatch_keystroke(*window, Keystroke::parse("a").unwrap());
        cx.dispatch_keystroke(*window, Keystroke::parse("ctrl-g").unwrap());

        window
            .update(cx, |test_view, _, _| {
                assert!(test_view.saw_key_down || test_view.saw_action);
                assert!(test_view.saw_key_down);
                assert!(test_view.saw_action);
            })
            .unwrap();
    }

    #[test]
    fn external_paths_exposes_path_helpers() {
        let paths = ExternalPaths::from_paths([
            PathBuf::from("/tmp/clip.mp4"),
            PathBuf::from("/tmp/subtitles.vtt"),
        ]);

        assert_eq!(paths.len(), 2);
        assert_eq!(paths.first().unwrap(), &PathBuf::from("/tmp/clip.mp4"));
        assert_eq!(
            paths.to_vec(),
            vec![
                PathBuf::from("/tmp/clip.mp4"),
                PathBuf::from("/tmp/subtitles.vtt")
            ]
        );
        assert!(!paths.is_empty());
    }

    #[test]
    fn file_drop_filter_normalizes_extensions_and_limits_count() {
        let filter = FileDropFilter::new()
            .extensions([".MP4", "mov", "mp4"])
            .max_files(2);
        assert_eq!(
            filter.allowed_extensions(),
            &["mov".to_string(), "mp4".to_string()]
        );
        assert_eq!(filter.configured_max_files(), Some(2));
        assert!(filter.validate().is_ok());

        let paths = ExternalPaths::from_paths([
            PathBuf::from("/tmp/a.MP4"),
            PathBuf::from("/tmp/b.mov"),
            PathBuf::from("/tmp/c.mp4"),
            PathBuf::from("/tmp/readme.txt"),
        ]);

        let matched = paths.filter_with(&filter);
        assert_eq!(
            matched.accepted(),
            &[PathBuf::from("/tmp/a.MP4"), PathBuf::from("/tmp/b.mov")]
        );
        assert_eq!(
            matched.rejected(),
            &[
                PathBuf::from("/tmp/c.mp4"),
                PathBuf::from("/tmp/readme.txt")
            ]
        );
        assert!(!matched.is_clean_accept());
        assert!(!matched.is_empty_accept());
    }

    #[test]
    fn file_drop_filter_accepts_any_extension_by_default() {
        let filter = FileDropFilter::new();
        let paths = ExternalPaths::from_paths([PathBuf::from("/tmp/archive.unknown")]);
        let matched = filter.evaluate(&paths);

        assert!(matched.is_clean_accept());
        assert_eq!(
            matched.into_accepted(),
            vec![PathBuf::from("/tmp/archive.unknown")]
        );
    }

    #[test]
    fn external_paths_can_return_clean_accepted_paths() {
        let filter = FileDropFilter::video().max_files(2);
        let clean = ExternalPaths::from_paths([
            PathBuf::from("/tmp/trailer.mp4"),
            PathBuf::from("/tmp/clip.MOV"),
        ]);
        let mixed = ExternalPaths::from_paths([
            PathBuf::from("/tmp/trailer.mp4"),
            PathBuf::from("/tmp/notes.txt"),
        ]);

        assert_eq!(
            clean.accepted_by(&filter),
            Some(vec![
                PathBuf::from("/tmp/trailer.mp4"),
                PathBuf::from("/tmp/clip.MOV")
            ])
        );
        assert_eq!(mixed.accepted_by(&filter), None);
    }

    #[test]
    fn external_drop_data_models_files_text_and_urls() {
        let filter = FileDropFilter::images().max_files(1);
        let data = ExternalDropData::from_paths([PathBuf::from("/tmp/poster.png")])
            .with_text("Poster")
            .with_url("https://example.com/poster.png");

        assert!(data.has_paths());
        assert!(data.has_text());
        assert!(data.has_urls());
        assert_eq!(data.text_value(), Some("Poster"));
        assert_eq!(data.urls(), &["https://example.com/poster.png".to_string()]);
        assert_eq!(
            data.accepted_paths_by(&filter),
            Some(vec![PathBuf::from("/tmp/poster.png")])
        );
    }

    #[test]
    fn external_drop_data_parses_uri_lists() {
        let data = ExternalDropData::from_uri_list(
            "# comment\nfile:///tmp/photo.png\nhttps://example.com/item\n\n",
        );

        assert_eq!(data.paths().paths(), &[PathBuf::from("/tmp/photo.png")]);
        assert_eq!(data.urls(), &["https://example.com/item".to_string()]);
        assert!(!data.has_text());
    }

    #[test]
    fn external_drop_data_extracts_urls_from_plain_text() {
        let data = ExternalDropData::from_plain_text(
            "Read this:\nhttps://example.com/a\nnot a url\nfile:///tmp/local.txt",
        );

        assert_eq!(
            data.text_value(),
            Some("Read this:\nhttps://example.com/a\nnot a url\nfile:///tmp/local.txt")
        );
        assert_eq!(
            data.urls(),
            &[
                "https://example.com/a".to_string(),
                "file:///tmp/local.txt".to_string()
            ]
        );
        assert!(data.paths().is_empty());
    }

    #[test]
    fn external_paths_convert_to_general_drop_data() {
        let paths = ExternalPaths::from_paths([PathBuf::from("/tmp/archive.zip")]);
        let data = paths.clone().into_drop_data();

        assert_eq!(ExternalDropData::from(paths), data);
        assert_eq!(data.paths().paths(), &[PathBuf::from("/tmp/archive.zip")]);
        assert!(!data.has_text());
        assert!(!data.has_urls());
    }

    #[test]
    fn external_drop_data_normalizes_drag_values() {
        let paths = ExternalPaths::from_paths([PathBuf::from("/tmp/movie.mp4")]);
        let from_paths = ExternalDropData::from_drag_value(&paths).unwrap();
        assert_eq!(
            from_paths.paths().paths(),
            &[PathBuf::from("/tmp/movie.mp4")]
        );

        let data = ExternalDropData::url("https://example.com/movie");
        let from_data = ExternalDropData::from_drag_value(&data).unwrap();
        assert_eq!(from_data, data);

        assert!(ExternalDropData::from_drag_value(&42usize).is_none());
    }

    #[test]
    fn external_drop_data_accepts_text_or_url_without_files() {
        let filter = FileDropFilter::video();

        assert!(ExternalDropData::text("label").accepted_by(&filter));
        assert!(ExternalDropData::url("https://example.com/video").accepted_by(&filter));
        assert!(
            ExternalDropData::from_paths([PathBuf::from("/tmp/trailer.mp4")]).accepted_by(&filter)
        );
        assert!(
            !ExternalDropData::from_paths([PathBuf::from("/tmp/poster.png")]).accepted_by(&filter)
        );
    }

    #[test]
    fn file_drop_filter_presets_cover_common_media_extensions() {
        assert!(FileDropFilter::images().accepts_path(std::path::Path::new("poster.webp")));
        assert!(FileDropFilter::audio().accepts_path(std::path::Path::new("track.flac")));
        assert!(FileDropFilter::video().accepts_path(std::path::Path::new("movie.mkv")));
        assert!(FileDropFilter::media().accepts_path(std::path::Path::new("movie.mp4")));
        assert!(FileDropFilter::media().accepts_path(std::path::Path::new("voice.opus")));
        assert!(!FileDropFilter::video().accepts_path(std::path::Path::new("notes.txt")));
        assert_eq!(
            FileDropFilter::single_file().configured_max_files(),
            Some(1)
        );
    }
}
