[package]
edition.workspace = true
name = "kael_util_macros"
rust-version.workspace = true
homepage.workspace = true
version.workspace = true
publish = true
description = "Utility macros for Kael"
keywords = ["macros", "utilities", "proc-macro", "kael"]
categories = ["development-tools::procedural-macro-helpers"]
authors.workspace = true
repository.workspace = true
readme = "README.md"
license.workspace = true

[features]
perf-enabled = ["perf"]

[lib]
name = "kael_util_macros"
path = "src/util_macros.rs"
doctest = false
proc-macro = true

[dependencies.perf]
path = "../perf"
package = "kael_perf"
version = "0.3.0"
optional = true

[dependencies.proc-macro2]
version = "1.0.93"

[dependencies.quote]
version = "1.0.9"

[dependencies.syn]
version = "2.0.101"
features = [
    "full",
    "extra-traits",
    "visit-mut",
]


[lints]
workspace = true
